from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    path("signin", views.signin, name="signin"),
    path("signup", views.signup, name="signup"),
    path("signout/", views.signout, name="signout"),
    path("index", views.index, name="index"),
    path("about", views.about, name="about"),
    path("lul", views.lul, name="lul"),
    # path('login', views.loginnew, name='login'),
    path("menu", views.menu, name="menu"),
    path("contact", views.contact, name="contact"),
    path("doctorForm", views.doctorFormView, name="doctorForm"),
    path("tutorForm", views.tutorFormView, name="tutorForm"),
    path(
        "service_providerForm",
        views.service_providerFormView,
        name="service_providerForm",
    ),
    path("logisticForm", views.logisticFormView, name="logisticForm"),
    path("otherForm", views.otherFormView, name="otherForm"),
    path("update", views.update, name="update"),
    path("doctor_update", views.doctor_update, name="doctor_update"),
    path("tutor_update", views.tutor_update, name="tutor_update"),
    path(
        "service_provider_update",
        views.service_provide_update,
        name="service_provide_update",
    ),
    path("logistic_update", views.logistic_update, name="logistic_update"),
    path("other_update", views.other_update, name="other_update"),
    path("find_doctor/<str:pk>", views.find_doctor, name="find_doctor"),
    path("find_tutor/<str:pk>", views.find_tutor, name="find_tutor"),
    path(
        "find_service_provider/<str:pk>",
        views.find_service_provider,
        name="find_service_provider",
    ),
    path("find_logistic/<str:pk>", views.find_logistic, name="find_logistic"),
    path("create_profile", views.create_profile, name="create_profile"),
    path("chat_masala", views.chat_masala, name="chat_masala"),
    path("chat/<int:sender>/<int:receiver>/", views.message_view, name="chat"),
    path("api/messages/<int:sender>/<int:receiver>/",views.message_list,name="message-detail",),
    path("api/messages/", views.message_list, name="message-list"),
    path("chat_view", views.chat_view, name="chat_view"),


    # path('chat/', views.chat_view, name='chats'),
    # path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    # path('api/messages/<int:sender>/<int:receiver>/', views.message_list, name='message-detail'),
    # path('api/messages/', views.message_list, name='message-list'),


    # path('chat/', views.chat_view, name='chats'),
    # path('chat/<str:sender>/<str:receiver>/', views.message_view, name='chat'),
    # # path('chat/&lt;int:sender>/&lt;int:receiver>/', views.message_view, name='chat'),
    # path('api/messages/&lt;int:sender>/&lt;int:receiver>/', views.message_list, name='message-detail'),
    # path('api/messages/', views.message_list, name='message-list'),
    # path('index', views.index, name='index'),
    # path('add_song', views.add_song, name='add_song'),
    # path('my_song', views.my_song, name='my_song'),
    # path('blog', views.blog, name='blog'),
    # path('contact', views.contact, name='contact'),
    # path('elements', views.elements, name='elements'),
    # path('track', views.track, name='track'),
    # path('about', views.about, name='about'),
    # path('blog', views.blog, name='blog'),
    # path('indexout', views.indexout, name='indexout'),
    # path('loginnew', views.loginnew, name='loginnew'),
    # path('public_song', views.public_song, name='public_song'),
    path("verify", views.verify, name="verify"),
    path("check_otp", views.check_otp, name="check_otp"),
    path("error", views.error, name="error"),
]


#     path('chat/<str:username>', views.chat_view, name='chat_view'),
#     path('chat/<str:sender>/<str:receiver>/', views.message_view, name='chat'),
#     path('api/messages/<str:sender>/<str:receiver>/', views.message_list, name='message-detail'),
#     path('api/messages/', views.message_list, name='message-list'),
