# Generated by Django 3.2.9 on 2021-12-10 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helperHubApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='flat_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='occupation',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Tutor', 'Tutor'), ('Service Provider', 'Service Provider'), ('Logistic', 'Logistic'), ('Other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('PHD', 'Doctor of Philosophy(PHD)'), ('BSC', 'Bachelor of Science(BSC)'), ('MSC', 'Master of Science(MSC)'), ('B.COM', 'Bachelor of Commerce(B.COM)'), ('M.COM', 'Master of Commerce(M.COM)'), ('B.Ed', 'Bachelor’s in Education(B.Ed)'), ('B.Tech', 'Bachelor of Technology(B.Tech)'), ('M.Tech', 'Master of Technology(M.Tech)'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Driver', 'Driver'), ('Mechanic', 'Mechanic'), ('Grocer', 'Grocer'), ('Carpenter', 'Carpenter'), ('Consultant', 'Consultant'), ('Chef', 'Chef'), ('Barber', 'Barber'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistic_type', models.CharField(choices=[('Recycling Logistics', 'Recycling Logistics'), ('Recovery Logistics', 'Recovery Logistics'), ('Sales Logistics', 'Sales Logistics'), ('Production Logistics', 'Production Logistics'), ('Procurement Logistics', 'Procurement Logistics'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('logistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('MBBS', 'Bachelor of Medicine, Bachelor of Surgery(MBBS)'), ('BDS', 'Bachelor of Dental Surgery(BDS)'), ('BAMS', 'Bachelor of Ayurvedic Medicine and Surgery(BAMS)'), ('BUMS', 'Bachelor of Unani Medicine and Surgery(BUMS)'), ('BHMS', 'Bachelor of Homeopathy Medicine and Surgery(BHMS)'), ('BYNS', 'Bachelor of Yoga and Naturopathy Sciences(BYNS)'), ('B.V.Sc & AH', 'Bachelor of Veterinary Sciences and Animal Husbandry(BVSc&AH)'), ('MD', 'Doctor of Medicine(MD)'), ('MS', 'Master of Surgery(MS)'), ('DM', 'Doctorate of Medicine(DM)')], max_length=50)),
                ('specialities_type', models.CharField(choices=[('ENT', 'Ear, Nose and Throat'), ('GS', 'General Surgery'), ('OP', 'Ophthalmology'), ('OR', 'Orthopaedics'), ('OAG', 'Obstetrics and Gynaecology'), ('DVL', 'Dermatology, Venerology and Leprosy'), ('AST', 'Anaesthesiology'), ('PSY', 'Psychiatry'), ('PTH', 'Pathology'), ('SVD', 'Skin and Venereal diseases'), ('PHRM', 'Pharmacology'), ('PMR', 'Physical Medicine and Rehabilitation'), ('PHY', 'Physiology'), ('CRD', 'Cardiology'), ('PDT', 'Paediatrics')], max_length=50)),
                ('dob', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender'), ('N', 'Prefer Not to Say')], max_length=1)),
                ('bio', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
