# Generated by Django 3.2.9 on 2021-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helperHubApp', '0002_auto_20211210_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='occupation',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Tutor', 'Tutor'), ('Service Provider', 'Service Provider'), ('Logistic', 'Logistic'), ('Other', 'Other')], max_length=50),
        ),
    ]
