# Generated by Django 2.2 on 2021-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helperHubApp', '0004_auto_20211211_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='degree_type',
            field=models.CharField(choices=[('MBBS', 'Bachelor of Medicine, Bachelor of Surgery(MBBS)'), ('BDS', 'Bachelor of Dental Surgery(BDS)'), ('BAMS', 'Bachelor of Ayurvedic Medicine and Surgery(BAMS)'), ('BAMS', 'Bachelor of Unani Medicine and Surgery(BUMS)'), ('BHMS', 'Bachelor of Homeopathy Medicine and Surgery(BHMS)'), ('BYNS', 'Bachelor of Yoga and Naturopathy Sciences(BYNS)'), ('B.V.Sc & AH', 'Bachelor of Veterinary Sciences and Animal Husbandry(BVSc&AH)'), ('MD', 'Doctor of Medicine(MD)'), ('MS', 'Master of Surgery(MS)'), ('DM', 'Doctorate of Medicine(DM)')], max_length=50),
        ),
    ]
