# Generated by Django 2.2 on 2021-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helperHubApp', '0005_auto_20211211_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
