# Generated by Django 2.2 on 2021-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helperHubApp', '0006_auto_20211211_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Prefer Not to Say', 'Prefer Not to Say')], max_length=50),
        ),
    ]
